version: '3'

services:
  postgres_db:
    restart: always
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=atomDB
      - POSTGRES_USER=dimitris
      - POSTGRES_PASSWORD=secret

  redis_db:
    restart: always
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
